{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ari_os",
    "module": "ari-tool-sdk",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "ari-tool-sdk-0.1.0.aar",
          "url": "ari-tool-sdk-0.1.0.aar",
          "size": 135234,
          "sha512": "696759096fb7c539f6532d39eb8f36c330b28090746523e460904babc3693e71e776cc13a533692ccee67cd6e84334a7d39c315bd3339864edd635ea4b08214f",
          "sha256": "79926aa2ef6e77fd524da8913f1f36e8642f3b60a0ddc0f79b86178657118c65",
          "sha1": "b766836b3f49de4566f216198c6646102d7e8ba4",
          "md5": "865669a9b35fb65359539670834e475a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "ari-tool-sdk-0.1.0.aar",
          "url": "ari-tool-sdk-0.1.0.aar",
          "size": 135234,
          "sha512": "696759096fb7c539f6532d39eb8f36c330b28090746523e460904babc3693e71e776cc13a533692ccee67cd6e84334a7d39c315bd3339864edd635ea4b08214f",
          "sha256": "79926aa2ef6e77fd524da8913f1f36e8642f3b60a0ddc0f79b86178657118c65",
          "sha1": "b766836b3f49de4566f216198c6646102d7e8ba4",
          "md5": "865669a9b35fb65359539670834e475a"
        }
      ]
    }
  ]
}
