{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ari_os",
    "module": "ari-tool-sdk",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "ari-tool-sdk-0.1.0.aar",
          "url": "ari-tool-sdk-0.1.0.aar",
          "size": 130447,
          "sha512": "105352d8e99dec412cc659ad3d32cf5fc1eafa4757d1715c678275bd664b276f677b91ceaa821c2c1ca80caa6b15ce82e67794cb7cad23ea52d97249452d1f7f",
          "sha256": "c2a10d21f425d882ede5927cad273bce8e6dfa5efbb6a8473fea64fcb14879ab",
          "sha1": "f86a3cf17241d792355ea0bb940da8f83a7e761d",
          "md5": "0e0f9c0b296f24a6ba694e282cf85480"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "ari-tool-sdk-0.1.0.aar",
          "url": "ari-tool-sdk-0.1.0.aar",
          "size": 130447,
          "sha512": "105352d8e99dec412cc659ad3d32cf5fc1eafa4757d1715c678275bd664b276f677b91ceaa821c2c1ca80caa6b15ce82e67794cb7cad23ea52d97249452d1f7f",
          "sha256": "c2a10d21f425d882ede5927cad273bce8e6dfa5efbb6a8473fea64fcb14879ab",
          "sha1": "f86a3cf17241d792355ea0bb940da8f83a7e761d",
          "md5": "0e0f9c0b296f24a6ba694e282cf85480"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ari-tool-sdk-0.1.0-sources.jar",
          "url": "ari-tool-sdk-0.1.0-sources.jar",
          "size": 28410,
          "sha512": "fad2a2db4c422059cf89745872ab83ccb881392b163b6843f453a6936f59bd43358c6beca7fd0cb520632da2a1b46a450ccad02e0b0f1d3ea3a355da8db39238",
          "sha256": "eaddbec80cf49d7b953946cadcbb0ce10acf80633eb50f9032c688276c466a67",
          "sha1": "229d0cd563761705489bfa8d2153ac468c202e1b",
          "md5": "a797b2bd2797eaec0fe09b014e379bd7"
        }
      ]
    }
  ]
}
